- pages/_app.tsx
- pages/global.css
- pages/style.module.scss
- src/common/css/colors.scss
- src/common/css/layout.scss
- src/components/form/form.module.scss
- Centered elements on disconnected screen
- Added global css file to center background image (removed the whitespace around it)
> Background button fix

- src/components/select/Select.tsx
Still small bug left, don't merge yet.
> Fixed trio selector logic

- pages/game/[room].tsx
This is fetching energyGain from the backend as updated in https://github.com/DeveloperKhan/pogo-web-backend/pull/2 
max energy is 100 :)  
this will also fit in nicely with https://github.com/DeveloperKhan/pogo-web/pull/14
> update energy for current Poke

- src/common/actions/getImage.ts
- src/common/actions/getMini.ts
- src/components/select/Select.tsx
- src/components/switch/Switch.tsx
> refactor image urls to use firebase

- package-lock.json
- package.json
- pages/_app.tsx
Use ws-heartbeat to send a message to server every 30s. There are no longer random disconnects
> Ws heartbeat

- pages/game/[room].tsx
- pages/game/style.module.scss
- src/components/game/charged/charged.module.scss
- src/components/game/field/Character.tsx
- src/components/game/field/character.module.scss
- src/components/game/switch/switch.module.scss
- src/components/team/team.module.scss
> Pokemon size

- pages/game/[room].tsx
- pages/game/style.module.scss
> slightly restyled messages, moved to top of field, added color

- package-lock.json
- pages/game/[room].tsx
Most of the changes are on the backend
> fix buffering on charge

- next.config.js
- package-lock.json
- package.json
Deployment suddenly started failing, gonna see if switching to a serverless target fixes it
> switch to serverless target

- src/common/actions/pokemonAPIActions.ts
- src/components/craft_team/CraftTeam.tsx
oops this should be on a new branch
> add validate pokemon endpoint

- src/components/team_member_selector/TeamMemberSelector.tsx
> fixed frontend making too many requests

- pages/game/[room].tsx
- pages/matchup/[room].tsx
- src/common/actions/getIVs.ts
- src/common/actions/getMaxLevel.ts
- src/components/craft_team/CraftTeam.tsx
- src/components/error_popup/ErrorPopup.tsx
- src/components/error_popup/style.module.scss
- src/components/game/stepper/Stepper.tsx
- src/components/modal/Modal.tsx
- src/components/modal/style.module.scss
- src/components/team/Team.tsx
- src/components/team_member_selector/TeamMemberSelector.tsx
> feat: add error popup to teambuilder

- pages/team/index.tsx
- src/common/actions/metaMap.ts
- src/common/actions/pokemonAPIActions.ts
- src/components/craft_team/CraftTeam.tsx
- src/components/error_popup/ErrorPopup.tsx
- src/components/team_member_selector/TeamMemberSelector.tsx
> feat: automatic team save

- pages/game/[room].tsx
- src/components/game/charged/Charged.tsx
- src/components/game/field/Character.tsx
- src/components/game/field/Field.tsx
- src/components/team_member_selector/TeamMemberSelector.tsx
> fix: switch with key to correct pokemon

- pages/team/index.tsx
- pages/team/style.module.scss
- src/components/import_team/ImportTeam.module.scss
- src/components/import_team/ImportTeam.tsx
> Added import and export functionality

- pages/game/[room].tsx
- src/components/error_popup/ErrorPopup.tsx
- src/components/form/Form.tsx
- src/components/team_member_selector/TeamMemberSelector.tsx
> Much frontend stuff

- pages/game/[room].tsx
> feat: pause after charge and faint

- pages/game/[room].tsx
- src/components/game/charged/Charged.tsx
- src/components/game/field/Character.tsx
> feat: send charge move messages no matter what

- pages/_app.tsx
- src/components/settings/preferences/Preferences.tsx
> Language selection now saves to localstorage

- pages/_app.tsx
- pages/end/[room].tsx
- pages/game/[room].tsx
- pages/game/style.module.scss
- src/context/GameEndContext.tsx
> Add good visible timers

- pages/index.tsx
- pages/matchup/[room].tsx
- src/components/form/Form.tsx
- src/components/team_selector/TeamSelector.tsx
- src/components/unauthenticated_popup/UnauthenticatedPopup.tsx
- src/context/SocketContext.tsx
> fix: quick play qol improvements

- pages/friends/index.tsx
> Fixed friends page from crashing when not logged in
